image: debian/stable
packages:
  - wget
sources:
  - https://git.sr.ht/~retzoh/Game_421
environment:
  REPOSITORY_NAME: Game_421
  PACKAGE_NAME: Game_421
  PACKAGE_FOLDER: Game_421
  PACKAGE_PATH: .
  GIT_SR_HT_URL: git@git.sr.ht:~retzoh/Game_421
  GITHUB_URL: git@github.com:Retzoh/game_421.git
secrets:
  - ed37ce69-d5be-42df-9b92-41471089d431  # ~/.ssh/known_hosts
  - 7331599a-5f2d-4b4f-9c92-e0a1483014e3  # ~/.ssh/.build_test_ssh_key
  - 899472e5-1ec8-4211-a00b-05a0d3eaf775  # ~/.ssh/.github_deploy_ssh_key
  - 20ceddf3-b6cb-4c2b-81c2-b6da58c48a4b  # ~/.cloudflare/api_keys
tasks:
- setup_nvm: |
    wget -nv -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

    echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.buildenv
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> .buildenv

- setup_npm: |
    nvm --version
    nvm install node

- install_dependencies: |
    npm --version
    cd $REPOSITORY_NAME

    npm install

    npm run elm --version

- test: |
    echo "TODO"

- build: |
    cd $REPOSITORY_NAME

    # npm run build
    npm run make
    npm run minify
    npm run escape_code
    npm run build_worker

- integration_tests: |
    echo "TODO"

- deploy_master: |
    ln -sf ~/.ssh/.build_test_ssh_key ~/.ssh/id_rsa

    cd $REPOSITORY_NAME
    git remote set-url origin $GIT_SR_HT_URL
    lines=`git diff --stat origin/master..HEAD | wc -l`
    if [ $lines -eq 0 ]
    then

    # deploy code
    git config --global user.email "~retzoh/builds@lists.sr.ht"
    git config --global user.name "Deploy"

    ln -sf ~/.ssh/.github_deploy_ssh_key ~/.ssh/id_rsa
    git checkout -B master -t origin/master
    git remote set-url origin $GITHUB_URL
    git push --set-upstream origin master

    # deploy worker
    . ~/.cloudflare/api_keys
    npm run publish

    else

    echo "Aborting github deployment: HEAD is dirty compared to master."

    fi
