image: debian/stable
packages:
  - wget
sources:
  - https://git.sr.ht/~retzoh/Game_421
environment:
  repository_name: Game_421
  package_name: Game_421
  package_folder: Game_421
  package_path: .
  git_sr_ht_url: git@git.sr.ht:~retzoh/Game_421
  github_url: git@github.com:Retzoh/game_421.git
secrets:
  - ed37ce69-d5be-42df-9b92-41471089d431  # ~/.ssh/known_hosts
  - 7331599a-5f2d-4b4f-9c92-e0a1483014e3  # ~/.ssh/.build_test_ssh_key
  - 899472e5-1ec8-4211-a00b-05a0d3eaf775  # ~/.ssh/.github_deploy_ssh_key
tasks:
- setup_nvm: |
    touch ~/.bashrc
    echo 'source ~/.bashrc' >> .buildenv
    wget -nv -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

    echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.buildenv
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> .buildenv

- setup_npm: |
    nvm --version
    nvm install node

- setup_elm: |
    npm --version

    npm install -g elm

    elm --version


- deploy_master_github: |
    ln -sf ~/.ssh/.build_test_ssh_key ~/.ssh/id_rsa

    cd $repository_name
    git remote set-url origin $git_sr_ht_url
    lines=`git diff --stat origin/master..HEAD | wc -l`
    if [ $lines -eq 0 ]
    then

    echo "pushing to github"
    git config --global user.email "~retzoh/builds@lists.sr.ht"
    git config --global user.name "Deploy"

    ln -sf ~/.ssh/.github_deploy_ssh_key ~/.ssh/id_rsa
    git checkout -B master -t origin/master
    git remote set-url origin $github_url
    git push --set-upstream origin master

    else

    echo "Aborting github deployment: HEAD is dirty compared to master."

    fi
